run: Plumb the exit code of a command back to run
TekWizely/run pull request #35
Opened 2021-09-01 13:43 UTC by rburchell

This allows failing a command if a run script fails, for example.

2021-09-03 18:23 UTC, TekWizely requested changes
Greetings!  Thanks so much for taking the time to create a PR.

I think this feature idea is extremely useful !

I do have some feedback on the approach, as `os.Exit(0)` seems harsh in general, and since exit aborts immediately, it feels wrong to do it where it currently resides since the condition is a pass-through of the run cmd and not really an error condition in Run proper.

Have a read of my review comments and lemme know what you think.

Thanks again, and I would love to hear how you are using Run if you have time to share?

Cheers,
-TW

2021-09-03 18:23 UTC, TekWizely commented on main.go
> +		os.Exit(exitCode)
So, you may be aware that `os.Exit` aborts immediately, ie no defers are called, etc.

As such, a few things jumped out to me in this review:
* `os.Exit(0)` seems a bit rough to force-exit in a non-error condition.
* These exit codes are not actually runtime Run error conditions, but the pass-through of the commands being run. So Run proper is not in an error state that needs immediate exit.
* BUT the *only* way to provide a non-0 exit code is through `os.Exit`

With all this in mind, I think a pattern like the following might be useful:
```
func main() {
    // Propagate cmd exit code if non-0
    // os.Exit aborts program immediately, so delay as long as possible
    // First defer in = last defer out
    // NOTE: Only set this from exit status of run commands
    //       Errors in Run proper should invoke os.Exit directly
    cmdExitCode := 0
    defer func() { if cmdExitCode != 0 { os.Exit(cmdExitCode) }}()
    // ...
}
```

2021-09-06 07:49 UTC, rburchell commented on main.go
> +	return 0
My personal preference is that the fewer codepaths that call exit, the better - but if you don't want to do that, then of course, that's fine. :)

2021-09-06 07:50 UTC, rburchell commented on main.go
> +		os.Exit(exitCode)
Using a deferred exit probably makes sense, yeah. I actually rediscovered this (the lack of defer being invoked) after submitting this PR because of another, unrelated personal project, so it's kind of funny that it also comes up here :)

2021-09-06 07:53 UTC, rburchell commented
As for my use of `run`, well... I have a set of shell scripts that do more or less the same thing, although in a less elegant way. They also lack a lot of features like command line argument handling, so `run` looks like a good fit to get something with more capabilities without the (painful) effort of continuing to extend a non-portable shell script harness.

As for what I use them for: all sorts of things, but usually general task-based jobs like "compile this project", "deploy this here", "start this in debug mode" etc.

On a related note, the one thing that I think `run` could use is an easier way to mark steps as dependent. Like, at the moment, I'm doing this:

```
##
# Runs unit tests
test:
    "${RUN}" -r "${RUNFILE}" build --builddir="build" --device="desktop" || exit 1
```

... but, subjectively, I find the syntax a little ugly. Not sure what to suggest to improve that, though, because I guess then you get into problems like "what if I only want to run it if $condition", "what if I don't want it to exit", etc.

2021-09-06 09:24 UTC, rburchell commented on main.go
> +	return 0
I think I see why. It's called (without a return or an exit) elsewhere in main, which this PR would break. I'll fix that.

2021-09-06 09:26 UTC, rburchell commented
I just directly took your suggestion for the defer approach :)

2021-09-07 02:00 UTC, TekWizely commented on main.go
> +			os.Exit(0)
Good find ! ... But 
If we're going to have the function return a value (even if its hard-coded to `0` currently), let's use it I suppose.  howzabout something like:
```
cmdExitCode = showVersion()
return // Exit early
```
Seems like it *should* exit the program naturally and avoid the os.Exit call - What do you think?
This should probably always have had a `return` here vs exit. Really can't figure out why I didn't do that before ...

2021-09-07 09:38 UTC, rburchell commented on main.go
> +			os.Exit(0)
Sure, that makes sense!

The only difficulty is then we need to use cmdExitCode unconditionally, not only for exit code 0. But I don't _think_ there's a problem with doing that, so I'll push it :)

2021-09-07 17:15 UTC, TekWizely commented
I want to keep the 0-check in the exit defer and was just expecting that version would result in exiting normally (it not exit(0))

Don't worry about changing it though - I actually have another slight mod I'm going to make, so I'll do it in a follow-up change once this is merged.

2021-09-07 17:16 UTC, merged

2021-09-07 17:17 UTC, TekWizely commented
Thanks so much for taking the time to contribute to Run  - I'm really stoked for this feature !

@all-contributors please add @rburchell for code